name: Cypress tests

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.7

      - name: Start frontend service
        run: |
          docker run -d --name frontend --network host -p 3000:3000 -v $PWD/application/web:/home/frontend node:20 bash -c "cd /home/frontend && npm install && npm run dev"

      - name: Start backend service
        run: |
          docker run -d --name backend --network host -p 3333:3333 -v $PWD/application/api:/home/backend node:20 bash -c "cd /home/backend && npm install && npm run dev"

      - name: Install dependencies
        run: |
          npm install

      - name: Run e2e tests
        run: |
          npx cypress run
